# -*- coding: utf-8 -*-
"""balance checknew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxyeh4Bpd2s5Lq3WPst71M1iaqkUL3Ww
"""

!python account_logic.py

!python main.py

!python display_menu.py

!python validation.py